Repository open-mmlab/mmsegmentation, pull requests merged in 2021-12, with the labels that each got.

#960 [Feature] Support Real-time model ERFNet
  README.md
  README_zh-CN.md
  configs/_base_/models/erfnet_fcn.py
  configs/erfnet/README.md
  configs/erfnet/erfnet.yml
  configs/erfnet/erfnet_fcn_4x4_512x1024_160k_cityscapes.py
  mmseg/models/backbones/__init__.py
  mmseg/models/backbones/erfnet.py
  model-index.yml
  tests/test_models/test_backbones/test_erfnet.py
Labels: WIP

#1091 [Fix] Fix test error when using --show-dir
  mmseg/apis/test.py
Labels: WIP

#1014 [Feature] Support video demo
  demo/video_demo.py
  docs/get_started.md
Labels: WIP, Merging

#1102 [Fix] Fix the bug that mit cannot process init_cfg
  mmseg/models/backbones/mit.py
  tests/test_models/test_backbones/test_mit.py
Labels: Merging

#1038 [Fix] Fix symlink failure on Windows
  setup.py
Labels: Merging

#1119 [Fix] Unified links of readthedocs in docs
  docs/conf.py
  docs_zh-CN/conf.py
Labels: Merging

#1127 [Fix] Add `<!-- [ABSTRACT] -->` in metafile.
  configs/ann/README.md
  configs/apcnet/README.md
  configs/bisenetv1/README.md
  configs/bisenetv2/README.md
  configs/ccnet/README.md
  configs/cgnet/README.md
  configs/danet/README.md
  configs/deeplabv3/README.md
  configs/deeplabv3plus/README.md
  configs/dmnet/README.md
  configs/dnlnet/README.md
  configs/dpt/README.md
  configs/emanet/README.md
  configs/encnet/README.md
  configs/erfnet/README.md
  configs/fastfcn/README.md
  configs/fastscnn/README.md
  configs/fcn/README.md
  configs/gcnet/README.md
  configs/hrnet/README.md
  configs/icnet/README.md
  configs/isanet/README.md
  configs/mobilenet_v2/README.md
  configs/mobilenet_v3/README.md
  configs/nonlocal_net/README.md
  configs/ocrnet/README.md
  configs/point_rend/README.md
  configs/psanet/README.md
  configs/pspnet/README.md
  configs/resnest/README.md
  configs/segformer/README.md
  configs/sem_fpn/README.md
  configs/setr/README.md
  configs/stdc/README.md
  configs/swin/README.md
  configs/twins/README.md
  configs/unet/README.md
  configs/upernet/README.md
  configs/vit/README.md
Labels: Merging

#1136 [Fix] Fix correct `num_classes` of HRNet in `LoveDA` dataset
  configs/hrnet/README.md
  configs/hrnet/fcn_hr18_512x512_80k_loveda.py
  configs/hrnet/hrnet.yml
Labels: Merging

#1128 [Docs] Refactor the structure of documentation
  .github/workflows/build.yml
  .gitignore
  README.md
  README_zh-CN.md
  demo/MMSegmentation_Tutorial.ipynb
  docs/en/Makefile
  docs/en/_static/css/readthedocs.css
  docs/en/_static/images/mmsegmentation.png
  docs/en/api.rst
  docs/en/changelog.md
  docs/en/conf.py
  docs/en/dataset_prepare.md
  docs/en/get_started.md
  docs/en/index.rst
  docs/en/inference.md
  docs/en/make.bat
  docs/en/model_zoo.md
  docs/en/stat.py
  docs/en/switch_language.md
  docs/en/train.md
  docs/en/tutorials/config.md
  docs/en/tutorials/customize_datasets.md
  docs/en/tutorials/customize_models.md
  docs/en/tutorials/customize_runtime.md
  docs/en/tutorials/data_pipeline.md
  docs/en/tutorials/index.rst
  docs/en/tutorials/training_tricks.md
  docs/en/useful_tools.md
  docs/zh_cn/Makefile
  docs/zh_cn/_static/css/readthedocs.css
  docs/zh_cn/_static/images/mmsegmentation.png
  docs/zh_cn/api.rst
  docs/zh_cn/conf.py
  docs/zh_cn/dataset_prepare.md
  docs/zh_cn/get_started.md
  docs/zh_cn/imgs/qq_group_qrcode.jpg
  docs/zh_cn/imgs/seggroup_qrcode.jpg
  docs/zh_cn/imgs/zhihu_qrcode.jpg
  docs/zh_cn/index.rst
  docs/zh_cn/inference.md
  docs/zh_cn/make.bat
  docs/zh_cn/model_zoo.md
  docs/zh_cn/stat.py
  docs/zh_cn/switch_language.md
  docs/zh_cn/train.md
  docs/zh_cn/tutorials/config.md
  docs/zh_cn/tutorials/customize_datasets.md
  docs/zh_cn/tutorials/customize_models.md
  docs/zh_cn/tutorials/customize_runtime.md
  docs/zh_cn/tutorials/data_pipeline.md
  docs/zh_cn/tutorials/index.rst
  docs/zh_cn/tutorials/training_tricks.md
  docs/zh_cn/useful_tools.md
  mmseg/datasets/custom.py
Labels: Merging

#1143 [Feature] Add UNet benchmark with multiple losses supervision.
  configs/unet/README.md
  configs/unet/deeplabv3_unet_s5-d16_ce-1.0-dice-3.0_128x128_40k_chase-db1.py
  configs/unet/deeplabv3_unet_s5-d16_ce-1.0-dice-3.0_128x128_40k_stare.py
  configs/unet/deeplabv3_unet_s5-d16_ce-1.0-dice-3.0_256x256_40k_hrf.py
  configs/unet/deeplabv3_unet_s5-d16_ce-1.0-dice-3.0_64x64_40k_drive.py
  configs/unet/fcn_unet_s5-d16_4x4_512x1024_160k_cityscapes.py
  configs/unet/fcn_unet_s5-d16_ce-1.0-dice-3.0_128x128_40k_chase-db1.py
  configs/unet/fcn_unet_s5-d16_ce-1.0-dice-3.0_128x128_40k_stare.py
  configs/unet/fcn_unet_s5-d16_ce-1.0-dice-3.0_256x256_40k_hrf.py
  configs/unet/fcn_unet_s5-d16_ce-1.0-dice-3.0_64x64_40k_drive.py
  configs/unet/pspnet_unet_s5-d16_ce-1.0-dice-3.0_128x128_40k_chase-db1.py
  configs/unet/pspnet_unet_s5-d16_ce-1.0-dice-3.0_128x128_40k_stare.py
  configs/unet/pspnet_unet_s5-d16_ce-1.0-dice-3.0_256x256_40k_hrf.py
  configs/unet/pspnet_unet_s5-d16_ce-1.0-dice-3.0_64x64_40k_drive.py
  configs/unet/unet.yml
Labels: WIP, Merging
