Repository open-mmlab/mmsegmentation, pull requests merged in 2022-12, with the labels that each got.

#2215 [Feature] Support MaskFormer(NeurIPS'2021) in MMSeg 1.x
  .circleci/test.yml
  .github/workflows/merge_stage_test.yml
  .github/workflows/pr_stage_test.yml
  README.md
  README_zh-CN.md
  configs/maskformer/README.md
  configs/maskformer/maskformer.yml
  configs/maskformer/maskformer_r101-d32_8xb2-160k_ade20k-512x512.py
  configs/maskformer/maskformer_r50-d32_8xb2-160k_ade20k-512x512.py
  configs/maskformer/maskformer_swin-s_upernet_8xb2-160k_ade20k-512x512.py
  configs/maskformer/maskformer_swin-t_upernet_8xb2-160k_ade20k-512x512.py
  mmseg/models/decode_heads/__init__.py
  mmseg/models/decode_heads/maskformer_head.py
  model-index.yml
  requirements/mminstall.txt
  tests/test_models/test_heads/test_maskformer_head.py
Labels: 1.x

#2255 [Feature] Support Mask2former in MMSeg 1.x
  README.md
  README_zh-CN.md
  configs/mask2former/README.md
  configs/mask2former/mask2former.yml
  configs/mask2former/mask2former_r101_8xb2-160k_ade20k-512x512.py
  configs/mask2former/mask2former_r101_8xb2-90k_cityscapes-512x1024.py
  configs/mask2former/mask2former_r50_8xb2-160k_ade20k-512x512.py
  configs/mask2former/mask2former_r50_8xb2-90k_cityscapes-512x1024.py
  configs/mask2former/mask2former_swin-b-in1k-384x384-pre_8xb2-160k_ade20k-640x640.py
  configs/mask2former/mask2former_swin-b-in22k-384x384-pre_8xb2-160k_ade20k-640x640.py
  configs/mask2former/mask2former_swin-b-in22k-384x384-pre_8xb2-90k_cityscapes-512x1024.py
  configs/mask2former/mask2former_swin-l-in22k-384x384-pre_8xb2-160k_ade20k-640x640.py
  configs/mask2former/mask2former_swin-l-in22k-384x384-pre_8xb2-90k_cityscapes-512x1024.py
  configs/mask2former/mask2former_swin-s_8xb2-160k_ade20k-512x512.py
  configs/mask2former/mask2former_swin-s_8xb2-90k_cityscapes-512x1024.py
  configs/mask2former/mask2former_swin-t_8xb2-160k_ade20k-512x512.py
  configs/mask2former/mask2former_swin-t_8xb2-90k_cityscapes-512x1024.py
  mmseg/models/decode_heads/__init__.py
  mmseg/models/decode_heads/mask2former_head.py
  model-index.yml
  tests/test_models/test_heads/test_mask2former_head.py
Labels: 1.x

#2402 [CI] Add torch1.13 checking in CI
  .circleci/test.yml
  .github/workflows/merge_stage_test.yml
  .github/workflows/pr_stage_test.yml
Labels: 1.x

#2387 [Doc] Add ZN datasets.md in dev-1.x
  docs/zh_cn/advanced_guides/datasets.md
Labels: Doc, 1.x

#2412 [Projects] Add 'Projects/' folder, and the first example project
  .github/workflows/merge_stage_test.yml
  .github/workflows/pr_stage_test.yml
  projects/README.md
  projects/example_project/README.md
  projects/example_project/configs/fcn_dummy-r50-d8_4xb2-40k_cityscapes-512x1024.py
  projects/example_project/dummy/__init__.py
  projects/example_project/dummy/dummy_resnet.py
Labels: 1.x

#2403 [Doc] Add dataflow document
  docs/en/advanced_guides/data_flow.md
Labels: Doc, 1.x

#2378 [Feature] Add Biomedical 3D array random crop transform
  mmseg/datasets/__init__.py
  mmseg/datasets/transforms/__init__.py
  mmseg/datasets/transforms/transforms.py
  tests/test_datasets/test_transform.py
Labels: medical

#2341 [Doc] Change some content from customize_runtime to engine ZN doc
  docs/zh_cn/advanced_guides/engine.md
Labels: Doc, 1.x

#2184 [Refactor] Support TTA
  configs/_base_/datasets/ade20k.py
  configs/_base_/datasets/ade20k_640x640.py
  configs/_base_/datasets/chase_db1.py
  configs/_base_/datasets/cityscapes.py
  configs/_base_/datasets/coco-stuff10k.py
  configs/_base_/datasets/coco-stuff164k.py
  configs/_base_/datasets/drive.py
  configs/_base_/datasets/hrf.py
  configs/_base_/datasets/isaid.py
  configs/_base_/datasets/loveda.py
  configs/_base_/datasets/pascal_context_59.py
  configs/_base_/datasets/pascal_voc12.py
  configs/_base_/datasets/pascal_voc12_aug.py
  configs/_base_/datasets/potsdam.py
  configs/_base_/datasets/stare.py
  configs/_base_/datasets/vaihingen.py
  configs/_base_/default_runtime.py
  mmseg/models/segmentors/__init__.py
  mmseg/models/segmentors/base.py
  mmseg/models/segmentors/seg_tta.py
  tests/test_datasets/test_tta.py
  tests/test_models/test_segmentors/test_seg_tta_model.py
  tests/test_models/test_segmentors/utils.py
  tools/test.py
Labels: 1.x
