Repository open-mmlab/mmsegmentation, pull requests merged in 2023-01, with the labels that each got.

#2373 [Feature] nnUNet-style Gaussian Noise and Blur
  mmseg/datasets/__init__.py
  mmseg/datasets/transforms/__init__.py
  mmseg/datasets/transforms/transforms.py
  tests/test_datasets/test_transform.py
Labels: medical

#2406 [Feature] Add BioMedicalRandomGamma
  docs/zh_cn/advanced_guides/datasets.md
  mmseg/datasets/__init__.py
  mmseg/datasets/transforms/__init__.py
  mmseg/datasets/transforms/transforms.py
  tests/test_datasets/test_transform.py
Labels: medical

#2450 Fix the docstring error in the class PascalContextDataset59
  mmseg/datasets/pascal_context.py
Labels: High Priority from Community

#2383 [Feature] Add BioMedical3DPad
  mmseg/datasets/__init__.py
  mmseg/datasets/transforms/__init__.py
  mmseg/datasets/transforms/transforms.py
  tests/test_datasets/test_transform.py
Labels: medical, High Priority from Community

#2400 CodeCamp #150 [Feature] Add ISNet
  projects/isnet/README.md
  projects/isnet/configs/isnet_r50-d8_8xb2-160k_cityscapes-512x1024.py
  projects/isnet/decode_heads/__init__.py
  projects/isnet/decode_heads/isnet_head.py
Labels: 1.x, High Priority from Community

#2465 [Doc] Update ZN dataset preparation of Synapse
  docs/en/user_guides/2_dataset_prepare.md
  docs/zh_cn/user_guides/2_dataset_prepare.md
Labels: Doc, 1.x

#2444 CodeCamp #151[Feature] Support HieraSeg on cityscapes
  projects/HieraSeg/README.md
  projects/HieraSeg/configs/_base_/datasets/cityscapes.py
  projects/HieraSeg/configs/_base_/default_runtime.py
  projects/HieraSeg/configs/_base_/models/deeplabv3plus_r50-d8_vd_contrast.py
  projects/HieraSeg/configs/_base_/schedules/schedule_80k.py
  projects/HieraSeg/configs/hieraseg/hieraseg_deeplabv3plus_r101-d8_4xb2-80l_cityscapes-512x1024.py
  projects/HieraSeg/decode_head/__init__.py
  projects/HieraSeg/decode_head/sep_aspp_contrast_head.py
  projects/HieraSeg/losses/__init__.py
  projects/HieraSeg/losses/hiera_triplet_loss_cityscape.py
  projects/HieraSeg/losses/tree_triplet_loss.py
Labels: 1.x, High Priority from Community

#2489 [Fix] Fix no revert_sync_batchnorm in image_demo of master branch
  demo/image_demo.py
Labels: bug

#2494 [Fix][Doc] Fix link of preprocessing and order of operations in ZN dataset.md doc.
  docs/zh_cn/advanced_guides/datasets.md
Labels: Doc, 1.x

#2502 [Doc] Add ZN Customized_runtime Doc in dev-1.x
  docs/zh_cn/advanced_guides/customize_runtime.md
Labels: Doc, 1.x

#2484 CodeCamp #1555[Feature] Support Mapillary Vistas Dataset
  projects/mapillary_dataset/README.md
  projects/mapillary_dataset/configs/_base_/datasets/mapillary_v1_2.py
  projects/mapillary_dataset/configs/_base_/datasets/mapillary_v2_0.py
  projects/mapillary_dataset/configs/deeplabv3plus_r101-d8_4xb2-240k_mapillay-512x1024.py
  projects/mapillary_dataset/docs/en/user_guides/2_dataset_prepare.md
  projects/mapillary_dataset/mmseg/datasets/mapillary_v1_2.py
  projects/mapillary_dataset/mmseg/datasets/mapillary_v2_0.py
  projects/mapillary_dataset/tools/dataset_converters/mapillary.py
Labels: 1.x, High Priority from Community

#2404 CodeCamp #141 [Feature] Add BioMedical3DRandomFlip.
  mmseg/datasets/__init__.py
  mmseg/datasets/transforms/__init__.py
  mmseg/datasets/transforms/transforms.py
  tests/test_datasets/test_transform.py
Labels: 1.x, medical, High Priority from Community

#2464 [Doc] Add EN datasets.md in dev-1.x
  docs/en/advanced_guides/datasets.md
Labels: Doc, 1.x

#2537 [Fix] Fix ERFNet URL in dev-1.x branch
  configs/erfnet/README.md
  configs/erfnet/erfnet.yml
Labels: 1.x
