Repository open-mmlab/mmsegmentation, pull requests merged in 2023-06, with the labels that each got.

#3012 [Enhancement] Change assertion logic inference cfg.model.test_cfg
  mmseg/models/segmentors/encoder_decoder.py
Labels: awaiting response

#2861 [Project] Medical semantic seg dataset: bccs
  projects/medical/2d_image/histopathology/breastCancerCellSegmentation/README.md
  projects/medical/2d_image/histopathology/breastCancerCellSegmentation/configs/breastCancerCellSegmentation_512x512.py
  projects/medical/2d_image/histopathology/breastCancerCellSegmentation/configs/fcn-unet-s5-d16_unet_1xb16-0.0001-20k_breastCancerCellSegmentation-512x512.py
  projects/medical/2d_image/histopathology/breastCancerCellSegmentation/configs/fcn-unet-s5-d16_unet_1xb16-0.001-20k_breastCancerCellSegmentation-512x512.py
  projects/medical/2d_image/histopathology/breastCancerCellSegmentation/configs/fcn-unet-s5-d16_unet_1xb16-0.01-20k_breastCancerCellSegmentation-512x512.py
  projects/medical/2d_image/histopathology/breastCancerCellSegmentation/datasets/breastCancerCellSegmentation_dataset.py
  projects/medical/2d_image/histopathology/breastCancerCellSegmentation/tools/prepare_dataset.py
Labels: WIP, awaiting response

#3136 [Fix] Fix dependency
  .circleci/test.yml
  configs/_base_/models/fpn_poolformer_s12.py
  configs/_base_/models/upernet_convnext.py
  configs/convnext/convnext-base_upernet_8xb2-amp-160k_ade20k-640x640.py
  configs/convnext/convnext-large_upernet_8xb2-amp-160k_ade20k-640x640.py
  configs/convnext/convnext-small_upernet_8xb2-amp-160k_ade20k-512x512.py
  configs/convnext/convnext-tiny_upernet_8xb2-amp-160k_ade20k-512x512.py
  configs/convnext/convnext-xlarge_upernet_8xb2-amp-160k_ade20k-640x640.py
  configs/poolformer/README.md
  docs/en/notes/faq.md
  docs/zh_cn/notes/faq.md
Labels: WIP
