Repository open-mmlab/mmsegmentation, pull requests merged in 2023-03, with the labels that each got.

#2609 [Feature] Support PIDNet
  README.md
  README_zh-CN.md
  configs/pidnet/README.md
  configs/pidnet/pidnet-l_2xb6-120k_1024x1024-cityscapes.py
  configs/pidnet/pidnet-m_2xb6-120k_1024x1024-cityscapes.py
  configs/pidnet/pidnet-s_2xb6-120k_1024x1024-cityscapes.py
  configs/pidnet/pidnet.yml
  mmseg/models/backbones/__init__.py
  mmseg/models/backbones/pidnet.py
  mmseg/models/decode_heads/__init__.py
  mmseg/models/decode_heads/pid_head.py
  mmseg/models/losses/__init__.py
  mmseg/models/losses/boundary_loss.py
  mmseg/models/losses/ohem_cross_entropy_loss.py
  mmseg/models/utils/__init__.py
  mmseg/models/utils/basic_block.py
  mmseg/models/utils/ppm.py
  model-index.yml
  tests/test_models/test_backbones/test_pidnet.py
  tests/test_models/test_heads/test_pidnet_head.py
Labels: 1.x

#2654 [Feature] Support SegNeXt in MMSegmentation 2.0
  README.md
  README_zh-CN.md
  configs/segnext/README.md
  configs/segnext/segnext.yml
  configs/segnext/segnext_mscan-b_1xb16-adamw-160k_ade20k-512x512.py
  configs/segnext/segnext_mscan-l_1xb16-adamw-160k_ade20k-512x512.py
  configs/segnext/segnext_mscan-s_1xb16-adamw-160k_ade20k-512x512.py
  configs/segnext/segnext_mscan-t_1xb16-adamw-160k_ade20k-512x512.py
  mmseg/models/backbones/__init__.py
  mmseg/models/backbones/mscan.py
  mmseg/models/decode_heads/__init__.py
  mmseg/models/decode_heads/ham_head.py
  model-index.yml
  tests/test_models/test_backbones/test_mscan.py
  tests/test_models/test_heads/test_ham_head.py
Labels: Algorithm, 1.x

#2426 [Docs] add deeplabv3 model structure
  configs/deeplabv3/README.md
Labels: High Priority from Community

#2710 [Feature] Add albu transform
  .circleci/test.yml
  .github/workflows/build.yml
  docs/en/get_started.md
  docs/zh_cn/get_started.md
  mmseg/datasets/pipelines/__init__.py
  mmseg/datasets/pipelines/transforms.py
  requirements/readthedocs.txt
  requirements/runtime.txt
  tests/test_data/test_transform.py
  tests/test_models/test_backbones/test_beit.py
  tests/test_models/test_backbones/test_mae.py
Labels: be volunteered, High Priority from Community
